config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :users, :controller => 'profiles' do
    resources :albums do
      resources :photos do
        member do 
          put "like", to: "photos#upvote"
          put "unlike", to: "photos#downvote"
        end
        resources :comments
      end
    end
  end

  

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :photos
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", high: "500x500#" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	acts_as_votable
	belongs_to :album
	has_many :comments

	def score
		self.get_upvotes.size - self.get_downvotes.size
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums

  acts_as_voter 

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	before_action :set_user, :authenticate_user!

	def index
		@albums = @user.albums.all
	end

	def show
		@album = @user.albums.find(params[:id])
	end

	def create
		@album = current_user.albums.new(album_params)
		if @album.save 
			redirect_to user_album_path @user, @album.id
		else
			render :new
		end
	end

	def edit
		@album = current_user.albums.find(params[:id])
	end

	def new
		@album = current_user.albums.new
	end

	def update
		@album = current_user.albums.find(params[:id])
		if @album.update album_params
			redirect_to :action => :show, :id => params[:id], @user => params[:user_id]
		else
			render :edit
		end
	end

	def destroy
		@album = current_user.albums.destroy(params[:id])
		redirect_to user_path @user
	end

	private 
	def album_params 
		params.require(:album).permit(:description, :title)
	end

	def set_user
		@user = User.find(params[:user_id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(profile)
  	user_path(profile)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_user, :set_photo, :set_album, :authenticate_user!

	def index
		@comments = @photo.comments
	end

	def show
		@comment = @photo.comments.find(params[:id])
	end

	def create
		@comment = @photo.comments.new(comment_params)
		if @comment.save 
			redirect_to user_album_photo_path(@album.user.id, @album, @photo)
		else
			render :new
		end
	end

	def edit
		@comment = @photo.comments.find(params[:id])
	end

	def new
		@comment = @photo.comments.new
		respond_to :html, :js
	end

	def update
		@comment = @photo.comments.find(params[:id])
		if @comment.update comment_params
			redirect_to :controller => 'photos', :action => 'show', :id => @photo, :user_id => @album.user.id, :album_id => @album
		else
			render :edit
		end
	end

	def destroy
		if @user == current_user
			@comment = @photo.comments.destroy(params[:id])
		end
		puts @user
		redirect_to :controller => :photos, :action => :show, :id => @photo.id, :user_id => current_user.id
	end

	private 
	def comment_params 
		params.require(:comment).permit(:content, :photo_id).merge(:owner => current_user.id)
	end

	def set_photo
		@photo = Photo.find(params[:photo_id])
	end

	def set_album
		@album = Album.find(params[:album_id])
	end

	def set_user
		@user = current_user
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!

	def index		
		@users = User.all
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	before_action :set_user, :set_album, :authenticate_user!

	def show
		@photo = @album.photos.find(params[:id])
	end

	def create
		@photo = @album.photos.new(photo_params)
		if @photo.save 
			redirect_to user_album_path current_user, @album
		else
			render :new
		end
	end

	def edit
		if @user == current_user
			@photo = @album.photos.find(params[:id])
		else
			redirect_to :action => :show, :id => params[:id]
		end
	end

	def new
		@photo = @album.photos.new
	end

	def update
		@photo = @album.photos.find(params[:id])
		if @photo.update photo_params
			redirect_to :action => :show, :id => params[:id], :album_id => params[:album_id]
		else
			render :edit
		end
	end

	def destroy
		if @user == current_user 
			@photo = @album.photos.destroy(params[:id])
		end
		puts @user
		redirect_to :controller => :albums, :action => :show, :id => @album.id, :user_id => @user.id
	end

	def upvote
		@photo = @album.photos.find(params[:id])
		@photo.upvote_by current_user
		redirect_to user_album_photo_path(@user, @album, @photo)
	end

	def downvote
  		@photo = @album.photos.find(params[:id])
  		if current_user.voted_up_on? @photo
  			@photo.downvote_by current_user
  		end
  		redirect_to user_album_photo_path(@user, @album, @photo)
	end

	private 
	def photo_params 
		params.require(:photo).permit(:description, :image)
	end

	def set_album
		@album = Album.find(params[:album_id])	
	end

	def set_user
		@user = User.find(params[:user_id])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	before_action :authenticate_user!

	def index
		@users = User.all 
	end

	def show 
		@user = User.find(params[:id])
	end

	def edit
		@user = current_user
	end

	def update 
		@user = current_user
		if @user.update user_params
			redirect_to :action => :show, :id => params[:id]
		else
			render :edit
		end
	end

	def destroy
		@user = User.delete(params[:id])
		redirect_to :action => :index
	end

	private
	def user_params 
		params.require(:user).permit(:email, :password, :name, :image)
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/albums/edit.html.haml
.container
  %h1.text-center.heading-font
    Edit album
  .row
    .col-md-6.col-md-offset-3
      = form_for [@user, @album] do |f|
        .form-group
          = f.label 'Title'
          = f.text_field :title, {:class => "form-control"}
        .form-group
          = f.label 'Description'
          = f.text_field :description, {:class => "form-control"}
        = f.submit 'Submit', :class => :"btn btn-primary"

app/views/albums/index.html.haml
.container
  %h1.text-center.heading-font
    All albums
  - if @user.id == current_user.id
    .row
      .col-md-12
        %ul.edit-buttons
          %li
            = link_to(new_user_album_path(current_user), {:class => "icon-left add-album-button"}) do
              %span
                Add album
  .row
  - @albums.each do |a|
    .col-md-4
      .image-box
        = image_tag a.photos.first.image.url(:high), {:class => "img-responsive"}
        = link_to({:controller => :albums, :action => :show, :id => a.id}, {:class => "image-hover image-shadow"}) do
          %h3.album-title
            = a.title
          %span.number-box.album-nr-photos
            = a.photos.count 
            photos
  
   

app/views/albums/new.html.haml
.container
  %h1.text-center.heading-font
    New album
  .row
    .col-md-6.col-md-offset-3
      = form_for [:user, @album] do |a|
        .form-group
          = a.label 'Description'
          = a.text_field :description, {:class => "form-control"}
        .form-group
          = a.label 'Title'
          = a.text_field :title, {:class => "form-control"}
        = a.submit :class => "btn btn-primary"

app/views/albums/show.html.haml
.container
  %h1.text-center.heading-font
    = @album.title
  %p.text-center.paragraph-font
    = @album.description
  - if @user == current_user
    .row
      .col-md-12
        %ul.edit-buttons
          %li
            = link_to({:controller => :photos, :action => :new, :album_id => @album.id}, :method => :get, :class => "icon-left add-photo-button") do
              %span
                Add photo
          %li
            = link_to({:controller => :albums, :action => :edit, :id => @album.id, :user_id => current_user}, :method => :get, :class => "icon-left edit-button") do
              %span
                Edit album
          %li
            = link_to({:controller => :albums, :action => :destroy, :id => @album.id}, :method => :delete, :class => "icon-left delete-album-button") do
              %span
                Delete album
  .row
    - @album.photos.each do |p|
      .col-md-4
        .image-box
          = image_tag p.image.url(:high), {:class => "img-responsive"}
          = link_to({:controller => :photos, :action => :show, :id => p.id, :album_id => @album.id}, {:class => "image-hover"}) do
            %span.number-box.photo-nr-likes
              = p.score

    

app/views/comments/_new_comment.html.haml
= form_for [:user, :album, :photo, @comment] do |f|
  = f.text_field :content, :class => "input-comment-block"
  = f.submit 'Create'

app/views/comments/edit.html.haml
%h1 Edit comment
= form_for [current_user, @album, @photo, @comment] do |f|
  = f.label 'Comment body'
  = f.text_field :content
  = f.submit 'Submit'

app/views/comments/index.html.haml
%h1 All comments
- @comments.each do |c|
  %p
  = link_to c.id, {:controller => :comments, :action => :show, :id => c.id}
  = link_to 'Add new comment', {:controller => :comments, :action => :new, :id => c.id, :photo_id => c.photo.id, :album_id => @photo.album_id, :user_id => current_user}, :method => :get

app/views/comments/new.html.haml
%h1 New Comment
= form_for [:user, :album, :photo, @comment] do |f|
  = f.label 'Comment body'
  = f.text_field :content
  = f.submit

app/views/comments/new.js.erb
var newComment = $('#new-comment')
newComment.html('<%=j render partial: "new_comment" %>')

app/views/comments/show.html.haml
%h1
  = @comment.content
= link_to :Back, {:controller => :photos, :action => :show, :id => @comment.photo.id}
= button_to :Edit, {:controller => :comments, :action => :edit, :id => @comment.id}, :method => :get

app/views/home/index.html.haml
.container
  %h3.text-center.heading-font
    Check out latest uploads
  %ul.users-align.user-block.heading-font
    - @users.each do |u|
      - if u.albums.last
        %li
          = image_tag u.image.url(:thumb), :class => "image-circle"
          = link_to(user_path(u.id)) do
            %span
              = u.name
        .row
          - u.albums.last.photos[0..2].each do |p|
            .col-md-4
              .image-box.image-box-home
                = image_tag p.image.url(:high), {:class => "img-responsive"}
                = link_to({:controller => :photos, :action => :show, :id => p.id, :album_id => p.album_id, :user_id => current_user.id}, {:class => "image-hover"}) do
                  %span.number-box.photo-nr-likes
                    = p.score

app/views/layouts/_footer.html.haml
%footer.footer-default
  .container
    .row
      %p.copyright-info
        %span.brand-name #Ginstagram
        was built by 
        %b
          Gina 
        and 
        %b 
          Vertigo Interactive Group
      %p.copyright-info Copyright &copy 2016

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "#Ginstagram", root_path, :class => "navbar-brand"

    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        = render partial: "layouts/header_logged_in"
      - else
        = render partial: "layouts/header_logged_out"
      

app/views/layouts/_header_logged_in.html.haml
%li.dropdown-header
  = link_to current_user.name, user_path(current_user), :method => :get
%li.dropdown
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    = image_tag current_user.image.url(:thumb), :class => "image-circle"
  %ul.dropdown-menu
    %li
      = link_to 'My Albums', user_albums_path(current_user), :method => :get
    %li
      = link_to 'Edit profile', edit_user_path(current_user), :method => :get
    %li
      = link_to 'All users', users_path(current_user), :method => :get
    %li.divider{:role => "separator"}
    %li
      = link_to 'Sign Out', destroy_user_session_path, :method => :delete

app/views/layouts/_header_logged_out.html.haml
%li.dropdown-header
	- unless request.path == "/users/sign_in"
		= link_to 'Sign In', user_session_path, :method => :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}

    %title Ginstagram
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render partial: "layouts/header"
    = yield
    = render partial: "layouts/footer"

app/views/photos/edit.html.haml
.container
  %h1.text-center.heading-font
    Edit photo description
  .row
    .col-md-6.col-md-offset-3
      = form_for [current_user, @album, @photo] do |f|
        .form-group
          = f.label 'Photo description'
          = f.text_field :description, {:class => "form-control"}
        = f.submit 'Submit', :class => "btn btn-primary"

app/views/photos/new.html.haml
.container
  %h1.text-center.heading-font
    New photo
  .row
    .col-md-6.col-md-offset-3
      = form_for [:user, :album, @photo] do |f|
        .form-group
          = f.label 'Photo description'
          = f.text_field :description, {:class => "form-control"}
        .form-group
          = f.file_field :image
        = f.submit :class => "btn btn-primary"

app/views/photos/show.html.haml
.container 
  .general-photo-border 
    .row
      .col-md-8
        .image-box.image-box-block
          = image_tag @photo.image.url(), :class => "img-responsive", :id => 'img-height'
          - if @user == current_user
            .image-hover
              %ul.action-box
                %li
                  = link_to({:controller => :photos, :action => :destroy, :id => @photo.id, :album_id => @photo.album.id}, :method => :delete, :class => "delete-hover-button") do
                    %span
                      Delete photo
                %li
                  = link_to({:controller => :photos, :action => :edit, :id => @photo.id, :album_id => @photo.album.id}, :method => :get, :class => "edit-hover-button") do
                    %span
                      Edit photo description    
      .col-md-4.heading-font.photo-description-font 
        .heading-photo-block 
          = image_tag current_user.image.url(:thumb), :class => "image-circle"
          %span
            %b
              = @user.name
          %h2.text-left.paragraph-font.paragraph-block
            = @photo.description
        .features-photo-block
          %ul.edit-buttons.edit-features-block
            %li
              = link_to(like_user_album_photo_path(@user, @album, @photo), :method => :put, :class => "icon-photo-left like-button") do
                %span
                  Like 
                %span
                  = @photo.get_likes.size
            %li
              = link_to(unlike_user_album_photo_path(@user, @album, @photo), :method => :put, :class => "icon-photo-left unlike-button") do
                %span
                  Unlike
                %span
                  = @photo.get_dislikes.size
            %li
              = link_to({ :controller => :comments, :action => :new, :photo_id => @photo.id, :album_id => @photo.album.id, :user_id => current_user}, :method => :get, :remote => true, :class => "icon-photo-left add-comment-button") do
                %span
                  Add comment   
        .action-photo-block.edit-buttons.edit-actions-block
          #new-comment     
          - @photo.comments.each do |c|
            .comment-essentials-block
              .action-username-block
                = image_tag User.find(c.owner).image.url(:thumb), :class => "image-circle comment-image"
                %b
                  = User.find(c.owner).name
              .action-comment-content-block
                = c.content
              - if current_user.id == c.owner
                .action-icon-block
                  .action-edit-button
                    = link_to'Edit comment', {:controller => :comments, :action => :edit, :id => c.id, :photo_id => c.photo.id, :album_id => @photo.album_id, :user_id => current_user}, :method => :get, :class => "icon-comment edit-comment-button"
                  .action-delete-button
                    = link_to 'Delete comment', {:controller => :comments, :action => :destroy, :id => c.id, :photo_id => c.photo.id, :album_id => @photo.album_id, :user_id => current_user}, :method => :delete, :class => "icon-comment delete-comment-button"

app/views/profiles/edit.html.haml
.container
  %h1.text-center.heading-font
    Edit profile
  .row
    .col-md-6.col-md-offset-3
      = form_for [current_user] do |f|
        .form-group
          = f.label 'Add name and surname'	
          = f.text_field :name, {:class =>"form-control"}
        .form-group
          = f.label 'Edit photo'
          = image_tag current_user.image.url(:medium), {:class => "img-responsive"}
          = f.file_field :image
        = f.submit 'Submit', :class => "btn btn-primary"

app/views/profiles/index.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
      %h2.text-center.heading-font
        All users
      %ul.users-align.heading-font
        - @users.each do |u|
          %li
            = link_to(user_path(u.id)) do
              = image_tag u.image.url(:thumb), :class => "image-circle"
              %span 
                = u.name
             

app/views/profiles/new.html.haml
%h1 New User
= form_for @user do |f|
  = f.label 'Register new user'
  = f.text_field :email
  = f.text_field :password
  = f.submit

app/views/profiles/show.html.haml
.container
  .row
    .col-md-3.col-md-offset-3
      = image_tag @user.image, :class => "img-responsive"
    .col-md-3
      %h2.text-left.heading-font
        = @user.name
      %ul.edit-buttons.edit-block
        %li
          = link_to(user_albums_path(@user.id), :method => :get, :class => "icon-left show-albums-button") do
            %span
              Show all albums

          - if @user == current_user
            %li
              = link_to({:controller => :profiles, :action => :edit, :id => current_user}, :method => :get, :class => "icon-left edit-button") do
                %span
                  Edit profile

            %li
              = link_to(@user, :method => :delete, :class => "icon-left delete-button") do
                %span
                  Delete profile

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/